name: onnxruntime

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "version tag"
        required: true
        default: "v1.6.0"

env:
  package_name: "onnxruntime"
  version: ${{ github.event.inputs.tag }}

jobs:
  init:
    runs-on: windows-latest
    outputs:
      output1: "${{ steps.create_release.outputs.upload_url }}"
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: ${{ github.event.inputs.tag }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.tag }}",
              sha: context.sha
            })

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: onnxruntime-${{ github.event.inputs.tag }}
          draft: false
          prerelease: false

  windows-build:
    needs: init
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        arch: ["x86", "x64"]

    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Server-Media-Foundation
        shell: powershell
        run: |
          Install-WindowsFeature Server-Media-Foundation

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Onnxruntime
        shell: cmd
        run: |
          git clone -b ${{ github.event.inputs.tag }} --recursive https://github.com/Microsoft/onnxruntime
          cd onnxruntime
          ..\build_onnx.bat ${{matrix.build_type}} ${{matrix.arch}}
          ls

      - name: Compress Package
        run: |
          Xcopy .\onnxruntime\build\Windows\${{matrix.build_type}}\${{matrix.build_type}}\onnxruntime.* .\install\lib /H/C/I
          .\clean_files.bat
          Xcopy .\onnxruntime\include\onnxruntime\core\session .\install\include\onnxruntime /H/C/I
          7z a onnxruntime.zip ./install/* -r

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.init.outputs.output1 }}
          asset_path: onnxruntime.zip
          asset_name: ${{ env.package_name }}-${{ env.version }}-${{matrix.build_type}}-${{matrix.arch}}-${{runner.os}}.zip
          asset_content_type: application/zip

  linux-build:
    needs: init
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        arch: ["x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build Onnxruntime
        shell: bash
        run: |
          git clone -b ${{ github.event.inputs.tag }} --recursive https://github.com/Microsoft/onnxruntime
          cd onnxruntime
          ./build.sh --build_shared_lib --parallel --config ${{matrix.build_type}}
          ls
      - name: Compress Package on Ubuntu
        run: |
          mkdir -p ./install/lib
          mkdir -p ./install/include/onnxruntime

          cp -r ./onnxruntime/build/Linux/${{matrix.build_type}}/libonnxruntime.so ./install/lib
          cp -r ./onnxruntime/include/onnxruntime/core/session/* ./install/include/onnxruntime
          cd ./install
          zip -r ${{ env.package_name }}-${{ env.version }}.zip ./*
          cd ..
          mv ./install/${{ env.package_name }}-${{ env.version }}.zip .
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.init.outputs.output1 }}
          asset_path: ${{ env.package_name }}-${{ env.version }}.zip
          asset_name: ${{ env.package_name }}-${{ env.version }}-${{matrix.build_type}}-${{matrix.arch}}-${{runner.os}}.zip
          asset_content_type: application/zip
